- hosts: localhost
  vars:
    source_key: "../.ssh/id_rsa_redcoreit_github"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa_redcoreit_github"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/git-setup.yml
    - include: tasks/core-setup.yml
    - include: tasks/zsh-setup.yml
    - include: tasks/nvim-setup.yml
    - include: tasks/mate-setup.yml
    - include: tasks/i3-setup.yml
    - include: tasks/brave.yml
    - include: tasks/rust.yml
    - include: tasks/dotfiles.yml
    - include: tasks/alacritty-setup.yml
    - include: tasks/productivity-tools.yml
    - include: tasks/zathura.yml
