- name: Set authorized key took from file
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa_redcoreit_github.pub"
  with_fileglob:
  - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"

- name: Evaluating the authentication agent & adding the key...
  shell: |
    eval "$(ssh-agent)"
    ssh-add {{ dest_key }}