- name: Installing stow
  become: true
  apt: name=stow
  tags:
    - install
    - dotfiles
    - stow

- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:redcoreit/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - install
    - dotfiles
    - stow

- name: Change stow-dotfiles permissions
  ansible.builtin.file:
    path: ../../scripts/stow-dotfiles
    mode: '0700'

- name: Stow dotfiles
  shell: ../../scripts/stow-dotfiles
  tags:
    - install
    - dotfiles
    - stow
