- name: Install Mate with i3
  become: true
  apt:
    name: [ "compton", "kitty", "i3", "ubuntu-mate-desktop" ]
  tags:
    - mate

- name: dconf i3
  shell: dconf write /org/mate/desktop/session/required-components/windowmanager "'i3'"
  tags:
    - mate

- name: dconf i3
  shell: dconf write /org/mate/desktop/background/show-desktop-icons "false"
  tags:
    - mate
