- name: check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes
  tags:
    - rust
    - alacritty

- name: Download Installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - rust
    - alacritty

- name: Install rust/cargo
  when: cargo_exists is failed
  ignore_errors: yes
  shell: |
    /tmp/sh.rustup.rs -y
    source ~/.cargo/env
  tags:
    - rust
    - alacritty

- name: Install rust-analyzer
  shell: |
    mkdir -p ~/.local/bin
    curl -L https://github.com/rust-lang/rust-analyzer/releases/latest/download/rust-analyzer-x86_64-unknown-linux-gnu.gz | gunzip -c - > ~/.local/bin/rust-analyzer
    chmod +x ~/.local/bin/rust-analyzer
  tags:
    - rust
    - alacritty

- name: Install rust nightly toolchain
  shell: rustup toolchain install nightly
  tags:
    - rust
    - alacritty
