#!/usr/bin/env bash

## Install ansible
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get update -y
sudo apt-get install -y curl git software-properties-common ansible

## pull ansible (not supports --ask-vault-pass)
# sudo ansible-pull -U https://github.com/redcoreit/ansible-linux.git

## clone repo no auth (note that it is not using https)
# git clone http://github.com/redcoreit/ansible-linux.git