#!/usr/bin/env zsh
rm ~/.zshrc

if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="i3,nvim,zsh,nitrogen,kitty"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS 
DOTFILES=$DOTFILES 

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done
popd